SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID
                        FROM ANIMAL_INS AS I
                        JOIN ANIMAL_OUTS AS O
                        ON I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY I.DATETIME
LIMIT 3