SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON C.CAR_ID = R.CAR_ID
WHERE C.CAR_TYPE = '¼¼´Ü'
AND MONTH(R.START_DATE) = 10
ORDER BY C.CAR_ID DESC