SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I
RIGHT JOIN ANIMAL_OUTS AS O
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.ANIMAL_ID NOT IN (SELECT O.ANIMAL_ID
                            FROM ANIMAL_INS AS I
                            JOIN ANIMAL_OUTS AS O
                            ON I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY ANIMAL_ID